# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartPlaylists', '0002_playlist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCombiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combiner_type', models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QueryCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('field_value_char', models.CharField(max_length=20)),
                ('field_value_int', models.IntegerField()),
                ('field_value_datetime', models.DateTimeField()),
                ('combiner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartPlaylists.QueryCombiner')),
            ],
        ),
        migrations.CreateModel(
            name='QueryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QueryOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_type', models.CharField(editable=False, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='query',
        ),
        migrations.AddField(
            model_name='querycondition',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartPlaylists.QueryField'),
        ),
        migrations.AddField(
            model_name='querycondition',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartPlaylists.Playlist'),
        ),
    ]
