# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicTool', '0005_auto_20160728_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='plex_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
